apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: grafana-pw
spec:
  vault:
    name: jyekeyvault01
    object:
      name: grafana-pw
      type: secret
  output:
    secret: 
      name: grafana-pw
      dataKey: password
      type: opaque