apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: grafana-password
spec:
  vault:
    name: jyeakskeyvault01
    object:
      name: grafana-secret
      type: secret
  output:
    secret: 
      name: grafana-password
      dataKey: password
      type: opaque