prometheus:
  ingress:
    enabled: true
    hostname: prometheus.wordpress.jyeclc.com
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
alertmanager:
  ingress:
    enabled: true
    hostname: alert.wordpress.jyeclc.com
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
