prometheus:
  ingress:
    enabled: true
    hostname: prometheus.wordpress.jyeclc.com  # NGINX Ingress 주소를 사용한다.
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
alertmanager:
  ingress:
    enabled: true
    hostname: alert.wordpress.jyeclc.com      # NGINX Ingress 주소를 사용한다.
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
